batta_staff/urls.py
from django.conf.urls import url

from batta_staff.views import (
    StaffListView, CreateStaffView, StaffCreditView, StaffDebitView,
    StaffUpdateView, NormalStaffDetailsView, AdvanceStaffCreditFormView,
    AdvanceStaffDetails, AdvanceStaffCreditUpdateView, NormalStaffDetailsReportsView,
    WeeklyStaffDetailsReportsView, OtherStaffCreditFormView, OtherStaffDebitView, OtherStaffDetails
)

urlpatterns = [
    url(r'^list/$', StaffListView.as_view(), name='list'),
    url(
        r'^list/(?P<season>[a-zA-Z0-9_-]+)/$',
        StaffListView.as_view(), name='list_filter'
    ),
    url(r'^create/$', CreateStaffView.as_view(), name='create'),
    url(
        r'^(?P<pk>\d+)/update/$',
        StaffUpdateView.as_view(), name='update'
     ),
    url(
        r'^(?P<pk>\d+)/credit/$',
        StaffCreditView.as_view(), name='credit'
     ),
    url(
        r'^(?P<pk>\d+)/debit/$',
        StaffDebitView.as_view(), name='debit'
    ),
    url(
        r'^(?P<pk>\d+)/details/$',
        NormalStaffDetailsView.as_view(), name='details'
    ),
    url(
        r'^(?P<pk>\d+)/details/reports/$',
        NormalStaffDetailsReportsView.as_view(), name='details_reports'
    ),
    url(
        r'^(?P<pk>\d+)/details/reports/(?P<season>[a-zA-Z0-9_-]+)/$',
        NormalStaffDetailsReportsView.as_view(), name='details_reports_fiter'
    ),
    url(
        r'^(?P<pk>\d+)/weekly/reports/$',
        WeeklyStaffDetailsReportsView.as_view(), name='weekly_reports'
    ),
    url(
        r'^(?P<pk>\d+)/weekly/reports/(?P<season>[a-zA-Z0-9_-]+)/$',
        WeeklyStaffDetailsReportsView.as_view(), name='weekly_reports_fiter'
    ),
    url(
        r'^(?P<pk>\d+)/credit/advance/$',
        AdvanceStaffCreditFormView.as_view(), name='credit_advance'
    ),
    url(
        r'^(?P<pk>\d+)/credit/update/$',
        AdvanceStaffCreditUpdateView.as_view(), name='update_advance'
    ),
    url(
        r'^(?P<pk>\d+)/details/advance/$',
        AdvanceStaffDetails.as_view(), name='details_advance'
    ),
    url(
        r'^(?P<pk>\d+)/details/advance/(?P<season>[a-zA-Z0-9_-]+)/$',
        AdvanceStaffDetails.as_view(), name='details_advance_fiter'
    ),
    url(
        r'^(?P<pk>\d+)/credit/other/$',
        OtherStaffCreditFormView.as_view(), name='credit_other'
    ),
    url(
        r'^(?P<pk>\d+)/debit/other/$',
        OtherStaffDebitView.as_view(), name='debit_other'
    ),
    url(
        r'^(?P<pk>\d+)/details/other/$',
        OtherStaffDetails.as_view(), name='details_other'
    ),
    url(
        r'^(?P<pk>\d+)/details/other/(?P<season>[a-zA-Z0-9_-]+)/$',
        OtherStaffDetails.as_view(), name='details_other_fiter'
    ),
]

common/urls.py
from django.conf.urls import url
from django.contrib import admin

from common.views import IndexView, LoginView, LogoutView, ReportsView, StaffJamahReportsView, QualityReportsView, TotalExpenseReportsView, KhattaReportsView

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(
        r'^index/(?P<season>[a-zA-Z0-9_-]+)/$',
        IndexView.as_view(), name='index_filter'
    ),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^reports/$', ReportsView.as_view(), name='reports'),
    url(r'^expense/reports/$', TotalExpenseReportsView.as_view(), name='expense_reports'),
    url(
        r'^reports/(?P<season>[a-zA-Z0-9_-]+)/$',
        ReportsView.as_view(), name='reports_filter'
    ),
    url(
        r'^khatta/reports/$', KhattaReportsView.as_view(), name='khatta_reports'
    ),
    url(
        r'^expense/reports/(?P<season>[a-zA-Z0-9_-]+)/$',
        TotalExpenseReportsView.as_view(), name='expense/reports/_filter'
    ),
    url(
        r'^quality/reports/$', QualityReportsView.as_view(),
        name='quality_reports'
    ),
    url(
        r'^staff/jamah/reports/$', StaffJamahReportsView.as_view(),
        name='staff_jamah_reports'
    ),
]

nawab_bricks_management/urls.py
from django.conf.urls import url,  include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('common.urls', namespace='common')),
    url(r'^customer/', include('batta_customers.urls', namespace='customer')),
    url(r'^stock/', include('batta_stock.urls', namespace='stock')),
    url(r'^sales/', include('batta_sales.urls', namespace='sales')),
    url(r'^expense/', include('batta_expense.urls', namespace='expense')),
    url(r'^staff/', include('batta_staff.urls', namespace='staff')),
    url(r'^koyla/', include('batta_koylas.urls', namespace='koyla')),
    url(r'^other/expense/', include('other_expense.urls', namespace='other_expense')),
    url(r'^account/', include('batta_account.urls', namespace='account')),

]

templates/staff/advance_staff_details.html
{% extends 'base.html' %}
{% block menu_staff %}active{% endblock %}

{% block content %}
    <br>
    {% if staff.staff_type == staff.STAFF_SALARY %}
        <a href="{% url 'staff:credit' pk=staff.id %}"><button type="button" class="btn btn-primary" style="float: left">Jamah</button></a> &nbsp;
    {% else %}
        <a href="{% url 'staff:credit_advance' pk=staff.id %}"><button type="button" class="btn btn-primary" style="float: left">Jamah</button></a> &nbsp;
    {% endif %}
    <a href="{% url 'staff:debit' pk=staff.id %}"><button type="button" class="btn btn-primary">Banam</button></a>
    <br>
    <h2 class="text-center">{{ staff.name }} / <small style="color: red">{{ staff.designation }}</small></h2>
{#    <div class="well">#}
        <div class="form-group col-lg-3 col-md-6 col-sm-6">
            <label for="sel1">Select list:</label>
            <select class="form-control" id="season_filter">
                <option>All Seasons</option>
                {% for season in seasons %}
                    <option>{{ season.season_year }}</option>
                {% endfor %}
            </select>
        </div>
{#    </div>#}
    {% if staff_credit %}
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h4><strong>Jamah Details</strong></h4>
                </div>
                <div class="panel-body table-responsive">
                    <table class="table table-striped table-advance table-hover ledger-table table-responsive">
                        <thead>
                        <tr>
                            <th><i class="fa fa-bullhorn"></i> Season </th>
                            <th><i class="fa fa-bookmark"></i> Date</th>
                            <th><i class="fa fa-bullhorn"></i> Page # </th>
                            <th><i class="fa fa-question-circle"></i> Details </th>
                            <th><i class="fa fa-question-circle"></i> Total Bricks</th>
                            <th><i class="fa fa-question-circle"></i> Bricks Rate</th>
                            <th><i class="fa fa-question-circle"></i> Weekly Kharcha</th>
                            <th><i class="fa fa-bookmark"></i> Net Amount</th>
                            <th>
                                Action
                            </th>
                        </tr>
                        </thead>
                        <tbody class="item-table-body">
                        {% for ledger in staff_credit %}
                            <tr>
                                <td>{{ ledger.season.season_year}}</td>
                                <td>{{ ledger.date_added }}</td>
                                <td>{{ ledger.page_no }}</td>
                                <td>{{ ledger.details }}</td>
                                <td>{{ ledger.total_bricks|floatformat:'-2' }}</td>
                                <td>{{ ledger.kharcha_rate|floatformat:'-2' }}</td>
                                <td>{{ ledger.weekly_amount|floatformat:'-2' }}</td>
                                <td>{{ ledger.net_payment|floatformat:'-2' }}</td>
                                <td><a href="{% url 'staff:update_advance' pk=ledger.id %}"><button class="btn btn-success btn-xs"><i class="fa fa-edit"></i></button></a></td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="panel-footer">
                    <strong style="color: black !important;">Total Bricks:</strong> {{ total_bricks|floatformat:'-2' }} &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <strong style="color: black !important;">Kharcha Payments:</strong> Rs. {{ payments|floatformat:'-2' }}<br>
                <strong style="color: black !important;">Grand Total:</strong> Rs. {{ net_amount|floatformat:'-2' }} &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <strong style="color: black !important;">Remaining Payments:</strong> Rs. {{ remaining_payment|floatformat:'-2' }}<br>
                </div>
            </div>
        </div>
    {% endif %}
    {% if staff_debit %}
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h4><strong>Banam Details</strong></h4>
                </div>
                <div class="panel-body table-responsive">
                    <table class="table table-striped table-advance table-hover payment-table table-responsive">
                        <thead>
                        <tr>
                            <th><i class="fa fa-question-circle"></i> Season</th>
                            <th><i class="fa fa-bullhorn"></i> Amount</th>
                            <th><i class="fa fa-bullhorn"></i> Page#</th>
                            <th><i class="fa fa-question-circle"></i> Details</th>
                            <th><i class="fa fa-bookmark"></i> Payment Date</th>
                        </tr>
                        </thead>
                        <tbody class="item-table-body">
                        {% for payment in staff_debit %}
                            <tr>
                                <td>{{ payment.season.season_year }}</td>
                                <td>{{ payment.amount|floatformat:-2}}</td>
                                <td>{{ payment.page_no }}</td>
                                <td>{{ payment.details }}</td>
                                <td>{{ payment.payment_date }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="panel-footer">
                    <strong style="color: red !important;">Total Payments without Weekly Report: <strong>Rs. {{ debit_amount|floatformat:-2 }}</strong></strong>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script>
        $(document).ready(function(){
            var details_url = '{% url 'staff:details_advance' pk=staff.id %}';
            $('#season_filter').on('change', function () {
                if ($(this).val() == 'All Seasons') {
                    window.location.href = details_url
                } else {
                    window.location.href = details_url + $(this).val() + '/';
                }
            });
            $('#season_filter option:contains("{{ season_kw }}")').prop('selected',true);

        });
    </script>
{% endblock %}

templates/staff/other_staff_details.html
{% extends 'base.html' %}
{% block menu_staff %}active{% endblock %}

{% block content %}
    <br>
    {% if staff.staff_type == staff.STAFF_SALARY %}
        <a href="{% url 'staff:credit' pk=staff.id %}"><button type="button" class="btn btn-primary" style="float: left">Credit</button></a> &nbsp;
    {% else %}
        <a href="{% url 'staff:credit_other' pk=staff.id %}"><button type="button" class="btn btn-primary" style="float: left">Jamah</button></a> &nbsp;
        <a href="{% url 'staff:debit_other' pk=staff.id %}"><button type="button" class="btn btn-primary">Banam</button></a>
    {% endif %}
    <br>
    <h2 class="text-center">{{ staff.name }} / <small style="color: red">{{ staff.designation }}</small></h2>
{#    <div class="well">#}
        <div class="form-group col-lg-3 col-md-6 col-sm-6">
            <label for="sel1">Select list:</label>
            <select class="form-control" id="season_filter">
                <option>All Seasons</option>
                {% for season in seasons %}
                    <option>{{ season.season_year }}</option>
                {% endfor %}
            </select>
        </div>
{#    </div>#}
    {% if staff_credit %}
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h4><strong>Jamah Details</strong></h4>
                </div>
                <div class="panel-body table-responsive">
                    <table class="table table-striped table-advance table-hover ledger-table table-responsive">
                        <thead>
                        <tr>
                            <th><i class="fa fa-bullhorn"></i> Season </th>
                            <th><i class="fa fa-bookmark"></i> Date</th>
                            <th><i class="fa fa-bullhorn"></i> Page # </th>
                            <th><i class="fa fa-question-circle"></i> Details </th>
                            <th><i class="fa fa-question-circle"></i> Total Bricks</th>
                            <th><i class="fa fa-question-circle"></i> Bricks Rate</th>
                            <th><i class="fa fa-bookmark"></i> Net Amount</th>
                            <th>
                                Action
                            </th>
                        </tr>
                        </thead>
                        <tbody class="item-table-body">
                        {% for ledger in staff_credit %}
                            <tr>
                                <td>{{ ledger.season.season_year}}</td>
                                <td>{{ ledger.date_added }}</td>
                                <td>{{ ledger.page_no }}</td>
                                <td>{{ ledger.details }}</td>
                                <td>{{ ledger.total_load|floatformat:'-2' }}</td>
                                <td>{{ ledger.rate|floatformat:'-2' }}</td>
                                <td>{{ ledger.total_payment|floatformat:'-2' }}</td>
                                <td><a href="{% url 'staff:update_advance' pk=ledger.id %}"><button class="btn btn-success btn-xs"><i class="fa fa-edit"></i></button></a></td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="panel-footer">
                    <strong style="color: black !important;">Total Bricks:</strong> {{ total_load|floatformat:'-2' }} &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <strong style="color: black !important;">Kharcha Payments:</strong> Rs. {{ payments|floatformat:'-2' }}<br>
                <strong style="color: black !important;">Grand Total:</strong> Rs. {{ net_amount|floatformat:'-2' }} &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <strong style="color: black !important;">Remaining Payments:</strong> Rs. {{ remaining_payment|floatformat:'-2' }}<br>
                </div>
            </div>
        </div>
    {% endif %}
    {% if staff_debit %}
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h4><strong>Banam Details</strong></h4>
                </div>
                <div class="panel-body table-responsive">
                    <table class="table table-striped table-advance table-hover payment-table table-responsive">
                        <thead>
                        <tr>
                            <th><i class="fa fa-question-circle"></i> Season</th>
                            <th><i class="fa fa-bullhorn"></i> Amount</th>
                            <th><i class="fa fa-bullhorn"></i> Page#</th>
                            <th><i class="fa fa-question-circle"></i> Details</th>
                            <th><i class="fa fa-bookmark"></i> Payment Date</th>
                        </tr>
                        </thead>
                        <tbody class="item-table-body">
                        {% for payment in staff_debit %}
                            <tr>
                                <td>{{ payment.season.season_year }}</td>
                                <td>{{ payment.amount|floatformat:-2}}</td>
                                <td>{{ payment.page_no }}</td>
                                <td>{{ payment.details }}</td>
                                <td>{{ payment.payment_date }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div class="panel-footer">
                    <strong style="color: red !important;">Total Payments without Weekly Report: <strong>Rs. {{ debit_amount|floatformat:-2 }}</strong></strong>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script>
        $(document).ready(function(){
            var details_other_url = '{% url 'staff:details_other' pk=staff.id %}';
            $('#season_filter').on('change', function () {
                if ($(this).val() == 'All Seasons') {
                    window.location.href = details_other_url
                } else {
                    window.location.href = details_other_url + $(this).val() + '/';
                }
            });
            $('#season_filter option:contains("{{ season_kw }}")').prop('selected',true);

        });
    </script>
{% endblock %}

templates/staff/staff_list.html
{% extends 'base.html' %}
{% block menu_staff %}active{% endblock %}
{% block sub_menu_all_staff %}active{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <br>
                <a href="{% url 'staff:create' %}"><button type="button" class="btn btn-primary">Add New Staff</button></a>
                <br><br>
                <div class="content-panel table-responsive">
                    <h2 class="text-center"><a href="#">Employees/Staffs</a></h2>
                    <div class="print-show-options" style="display:ruby-text-container; color: teal">
                        {% if season_kw %}
                            <h3 class="text-center">Season: {{ season_kw }}</h3>
                        {% endif %}
                    </div>
                    <br>
                    <div class="remove-print-display">
                        <div class="col-lg-6">
                            <div class="input-group custom-search-form col-md-10" style="left: 5px">
                                <input type="text" class="form-control search-staff" placeholder="Search...">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                        </div>
                        {#<div class="col-lg-2">#}
                            {#<select class="form-control" id="season_filter">#}
                                {#<option>All Seasons</option>#}
                                {#{% for season in seasons %}#}
                                    {#<option>{{ season.season_year }}</option>#}
                                {#{% endfor %}#}
                            {#</select>#}
                        {#</div>#}
                    </div>
                    <div style="float: right; padding: 10px;" class="remove-print-display">
                        <strong><span style="color: #428bca !important; font-size: 16px">Total Staff:</span><span style="color: red !important; font-size: 16px"> {{ total_staff|floatformat:'-2' }}</span></strong>&nbsp;&nbsp;&nbsp;
                        <strong><span style="color: #428bca !important; font-size: 16px">Remaining Balance:</span><span style="color: red !important; font-size: 16px"> {{ remaining_balance|floatformat:'-2' }}</span></strong>
                    </div>
                    <hr>
                    <table class="table table-striped table-advance table-hover table-bordered staffs-table table-responsive">
                        <thead style="background-color: teal !important;">
                        <tr style="color: white">
                            <th>S.No</th>
                            <th class="text-center"> Name</th>
                            {#<th><i class="fa fa-question-circle"></i> Bhatta</th>#}
                            {#<th><i class=" fa fa-edit"></i> CNIC</th>#}
                            {#<th><i class=" fa fa-edit"></i> Mobile</th>#}
                            <th class="text-center"> Staff Type</th>
                            <th class="text-center"> Designation</th>
                            <th class="text-center"> Joining Date</th>
                            <th class="text-center"> Rate / Salary</th>
                            <th class="text-center"> R / Balance</th>
                            <th class="text-center"> STAFF PAYMENT Status</th>
                            <th class="text-center">Actions</th>
                        </tr>
                        </thead>
                        <tbody class="staff-table-body">
                        {% if not object_list %}
                            <tr><td colspan="9" class="text-center">Record Not Found</td></tr>
                        {% endif %}
                        {% for staff in object_list %}
                            <tr style="color: black; font-weight: bold">
                                <td class="text-center">{{ forloop.counter }}</td>
                                <td class="text-center"><a href="#">{{ staff.name|title }}</a></td>
                                {#<td>{{ staff.bhatta.code}}</td>#}
                                {#<td>{{ staff.cnic }}</td>#}
                                {#<td>{{ staff.mobile_no }}</td>#}
                                <td class="text-center">{{ staff.staff_type }}</td>
                                <td class="text-center">{{ staff.designation }}</td>
                                <td class="text-center">{{ staff.joining_date }}</td>
                                <td class="text-center">{{ staff.rate }}</td>
                                {% if staff.staff_type == staff.STAFF_SALARY %}
                                {#<td>{{ staff.remaining_balance|floatformat:-2}}</td>#}
                                <td class="text-center">{{ staff.remaining_pay|floatformat:-2}}</td>
                                <td class="text-center">{{ staff.staff_payment_action }}</td>
                                {% else %}
                                <td class="text-center">{{ staff.remaining_amount|floatformat:-2}}</td>
                                <td class="text-center">{{ staff.staff_payment_action }}</td>
                                {% endif %}
                                <td class="text-center">
                                    <a href="{% url 'staff:update' pk=staff.id %}"><button class="btn btn-primary btn-xs">Update</button></a>
                                    {% if staff.staff_type == staff.STAFF_SALARY %}
                                        <a href="{% url 'staff:details' pk=staff.id %}"><button class="btn btn-success btn-xs">View</button></a>
                                        <a href="{% url 'staff:details_reports' pk=staff.id %}"><button class="btn btn-warning btn-xs">Reports</button></a>
                                    {% elif staff.staff_type == staff.STAFF_WEEKLY %}
                                        <a href="{% url 'staff:details_advance' pk=staff.id %}"><button class="btn btn-warning btn-xs">View</button></a>
                                        <a href="{% url 'staff:weekly_reports' pk=staff.id %}"><button class="btn btn-danger btn-xs">Reports</button></a>
                                    {% elif staff.staff_type == staff.STAFF_OTHER %}
                                        <a href="{% url 'staff:details_other' pk=staff.id %}"><button class="btn btn-danger btn-xs">View</button></a>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

<!-- Add Staff Modal HTML -->
	<div id="addstaff" class="modal fade">
		<div class="modal-dialog">
			<div class="modal-content">
				<form action="{% url 'staff:create' %}" method="post" autocomplete="off">
                    {% csrf_token %}
					<div class="modal-header">
						<h4 class="modal-title text-center">Add Staff</h4>
						<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					</div>
					<div class="modal-body">
                        <div class="col-md-6 form-group">
                            <label class="form-control-label">Staff Name <span style="color:red">*</span></label>
                            <input type="text" name="name" class="form-control form-control-alternative" placeholder="Add Staff Name" required>
                        </div>

                    <div class="col-md-6 form-group">
                        <label class="form-control-label">Bhatta<span style="color:red">*</span></label>
                            <select class="form-control bhatta_name" name="bhatta_name" id="bhatta_list" autocomplete="off" list="bhatta_list">
                            {% for bhatta in bhattas %}
                            <option value="{{ bhatta.name }}">{{ bhatta.code }}</option>
                            {% endfor %}
                         </select>
                    </div>

                    <div class="col-md-6 form-group">
                        <label class="form-control-label" name="customer_type">Staff Type<span style="color:red">*</span></label>
                        <input type="text" class="form-control staff_type" name="staff_type" autocomplete="off" placeholder="Select type" list="staff_type_list">
                        <datalist id="staff_type_list">
                            <option value="Salary Staff"></option>
                            <option value="Weekly Staff"></option>
                            <option value="Other Staff"></option>
                        </datalist>
                    </div>

                    <div class="col-md-6 form-group">
                        <label class="form-control-label">Designation <span style="color:red"></span></label>
                        <input type="text" name="designation" class="form-control form-control-alternative" placeholder="Designation">
                    </div>

                    <div class="col-md-6 form-group">
                        <label class="form-control-label">Rate <span style="color:red"></span></label>
                        <input type="text" name="rate" class="form-control form-control-alternative" placeholder="Rate">
                    </div>

                    <div class="col-md-6 form-group">
                        <label class="form-control-label">Mobile <span style="color:red"></span></label>
                        <input type="text" name="mobile_no" class="form-control form-control-alternative" placeholder="Mobile">
                    </div>

                    <div class="col-md-6 form-group">
                        <label class="form-control-label">Joining Date <span style="color:red"></span></label>
                        <input type="date" name="joining_date" class="form-control form-control-alternative" placeholder="Add Joining Date" >
                    </div>

                        <div class="col-md-6 form-group">
                            <label class="form-control-label">Leaving Date  <span style="color:red"></span></label>
                            <input type="date" name="leaving_date" class="form-control form-control-alternative" placeholder="Add Leaving Date" >
                        </div>
                    </div>
                    <br>
					<div class="modal-footer">
						<input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel">
						<input type="submit" class="btn btn-success" value="Add">
					</div>
				</form>
			</div>
		</div>
	</div>
    <!-- Add Staff Modal End -->

{% endblock %}
{% block scripts %}
    {{ block.super }}
    <script>
        $(document).ready(function() {
            $(".search-staff").on("keyup", function () {
                var value = $(this).val().toLowerCase();
                $(".staff-table-body tr").filter(function () {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });

            var staffs_url = '{% url "staff:list" %}';
            $('#season_filter').on('change', function () {
                if ($(this).val() == 'All Seasons') {
                    window.location.href = staffs_url
                } else {
                    window.location.href = staffs_url + $(this).val() + '/';
                }
            });
            $('#season_filter option:contains("{{ season_kw }}")').prop('selected',true);

        });
    </script>
{% endblock %}