batta_koylas/urls.py
from django.conf.urls import url

from batta_koylas.views import (
    Koylas, KoylaAddFormView,
    KoylaLedgerFormView, KoylaLedgerPaymentFormView, KoylaLedgerDetailView, KoylaReportsView, KoylaUpdateView
)

urlpatterns = [
    url(r'^$', Koylas.as_view(), name='list'),
    url(r'^add/$', KoylaAddFormView.as_view(), name='add'),
    url(
        r'^(?P<pk>\d+)/update/$',
        KoylaUpdateView.as_view(),
        name='update'
    ),
    url(
        r'^(?P<pk>\d+)/add/ledger/$',
        KoylaLedgerFormView.as_view(),
        name='add_ledger'
    ),
    url(
        r'^(?P<pk>\d+)/payment/ledger/$',
        KoylaLedgerPaymentFormView.as_view(),
        name='payment_ledger'
    ),
    url(
        r'^(?P<koyla_id>\d+)/ledger/details/$',
        KoylaLedgerDetailView.as_view(),
        name='ledger_details'
    ),
    url(
        r'^(?P<koyla_id>\d+)/reports/$',
        KoylaReportsView.as_view(),
        name='reports'
    ),
]

batta_sales/urls.py
from django.conf.urls import url
from . import views
from batta_sales.views import (
    CreateInvoiceFormView, StockItemsAPIView, CreateInvoiceAPIView,
    InvoicesListView, InvoiceDetailsView
)

urlpatterns = [
    url(r'^invoices/$', InvoicesListView.as_view(), name='invoices'),
    url(
        r'^invoices/(?P<season>[a-zA-Z0-9_-]+)/$',
        InvoicesListView.as_view(), name='invoices_filter'
    ),
    url(r'^create/$', CreateInvoiceFormView.as_view(), name='create_invoice'),
    url(r'^(?P<pk>\d+)/invoice/delete/$', views.DeleteInvoices, name='invoice_delete'),
    url(
        r'stock/items/api/$', StockItemsAPIView.as_view(),
        name='stock_items_api'
    ),
    url(
        r'create/invoice/api/$', CreateInvoiceAPIView.as_view(),
        name='create_invoice_api'
    ),
    url(
        r'^invoice/(?P<pk>\d+)/details/$',
        InvoiceDetailsView.as_view(),
        name='invoice_details'
    ),
]

batta_staff/urls.py
from django.conf.urls import url

from batta_staff.views import (
    StaffListView, CreateStaffView, StaffCreditView, StaffDebitView,
    StaffUpdateView, NormalStaffDetailsView, AdvanceStaffCreditFormView,
    AdvanceStaffDetails, AdvanceStaffCreditUpdateView, NormalStaffDetailsReportsView,
    WeeklyStaffDetailsReportsView, OtherStaffCreditFormView, OtherStaffDebitView, OtherStaffDetails
)

urlpatterns = [
    url(r'^list/$', StaffListView.as_view(), name='list'),
    url(
        r'^list/(?P<season>[a-zA-Z0-9_-]+)/$',
        StaffListView.as_view(), name='list_filter'
    ),
    url(r'^create/$', CreateStaffView.as_view(), name='create'),
    url(
        r'^(?P<pk>\d+)/update/$',
        StaffUpdateView.as_view(), name='update'
     ),
    url(
        r'^(?P<pk>\d+)/credit/$',
        StaffCreditView.as_view(), name='credit'
     ),
    url(
        r'^(?P<pk>\d+)/debit/$',
        StaffDebitView.as_view(), name='debit'
    ),
    url(
        r'^(?P<pk>\d+)/details/$',
        NormalStaffDetailsView.as_view(), name='details'
    ),
    url(
        r'^(?P<pk>\d+)/details/reports/$',
        NormalStaffDetailsReportsView.as_view(), name='details_reports'
    ),
    url(
        r'^(?P<pk>\d+)/details/reports/(?P<season>[a-zA-Z0-9_-]+)/$',
        NormalStaffDetailsReportsView.as_view(), name='details_reports_fiter'
    ),
    url(
        r'^(?P<pk>\d+)/weekly/reports/$',
        WeeklyStaffDetailsReportsView.as_view(), name='weekly_reports'
    ),
    url(
        r'^(?P<pk>\d+)/weekly/reports/(?P<season>[a-zA-Z0-9_-]+)/$',
        WeeklyStaffDetailsReportsView.as_view(), name='weekly_reports_fiter'
    ),
    url(
        r'^(?P<pk>\d+)/credit/advance/$',
        AdvanceStaffCreditFormView.as_view(), name='credit_advance'
    ),
    url(
        r'^(?P<pk>\d+)/credit/update/$',
        AdvanceStaffCreditUpdateView.as_view(), name='update_advance'
    ),
    url(
        r'^(?P<pk>\d+)/details/advance/$',
        AdvanceStaffDetails.as_view(), name='details_advance'
    ),
    url(
        r'^(?P<pk>\d+)/details/advance/(?P<season>[a-zA-Z0-9_-]+)/$',
        AdvanceStaffDetails.as_view(), name='details_advance_fiter'
    ),
    url(
        r'^(?P<pk>\d+)/credit/other/$',
        OtherStaffCreditFormView.as_view(), name='credit_other'
    ),
    url(
        r'^(?P<pk>\d+)/debit/other/$',
        OtherStaffDebitView.as_view(), name='debit_other'
    ),
    url(
        r'^(?P<pk>\d+)/details/other/$',
        OtherStaffDetails.as_view(), name='details_other'
    ),
    url(
        r'^(?P<pk>\d+)/details/other/(?P<season>[a-zA-Z0-9_-]+)/$',
        OtherStaffDetails.as_view(), name='details_other_fiter'
    ),
]

batta_stock/urls.py
from django.conf.urls import url

from batta_stock.views import (
    StockView, AddItemFormView, AddNewStockFormView, StockOutFormView,
    ItemStockDetailsView, AvailableStockAPIView, StockReportsView
)


urlpatterns = [
    url(r'^items/$', StockView.as_view(), name='item_list'),
    url(
        r'^items/(?P<season>[a-zA-Z0-9_-]+)/$',
        StockView.as_view(), name='item_list_filter'
    ),
    url(r'^item/add/$', AddItemFormView.as_view(), name='item_add'),
    url(
        r'^item/(?P<pk>\d+)/stock-in/$',
        AddNewStockFormView.as_view(), name='stock_in'
    ),
    url(
        r'^item/(?P<pk>\d+)/stock-out/$',
        StockOutFormView.as_view(), name='stock_out'
    ),
    url(
        r'^item/(?P<item_id>\d+)/details/$',
        ItemStockDetailsView.as_view(), name='item_stock_details'
    ),
    url(
        r'^item/(?P<item_id>\d+)/details/(?P<season>[a-zA-Z0-9_-]+)/$',
        ItemStockDetailsView.as_view(), name='item_stock_details_filter'
    ),
    url(
        r'^item/available/api/', AvailableStockAPIView.as_view(),
        name='available_item_api'
    ),
    url(r'^reports/$', StockReportsView.as_view(), name='stock_reports'),
    url(
        r'^reports/(?P<season>[a-zA-Z0-9_-]+)/$', StockReportsView.as_view(),
        name='stock_reports_filter'
    ),
]

common/urls.py
from django.conf.urls import url
from django.contrib import admin

from common.views import IndexView, LoginView, LogoutView, ReportsView, StaffJamahReportsView, QualityReportsView, TotalExpenseReportsView, KhattaReportsView

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(
        r'^index/(?P<season>[a-zA-Z0-9_-]+)/$',
        IndexView.as_view(), name='index_filter'
    ),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^reports/$', ReportsView.as_view(), name='reports'),
    url(r'^expense/reports/$', TotalExpenseReportsView.as_view(), name='expense_reports'),
    url(
        r'^reports/(?P<season>[a-zA-Z0-9_-]+)/$',
        ReportsView.as_view(), name='reports_filter'
    ),
    url(
        r'^khatta/reports/$', KhattaReportsView.as_view(), name='khatta_reports'
    ),
    url(
        r'^expense/reports/(?P<season>[a-zA-Z0-9_-]+)/$',
        TotalExpenseReportsView.as_view(), name='expense/reports/_filter'
    ),
    url(
        r'^quality/reports/$', QualityReportsView.as_view(),
        name='quality_reports'
    ),
    url(
        r'^staff/jamah/reports/$', StaffJamahReportsView.as_view(),
        name='staff_jamah_reports'
    ),
]

nawab_bricks_management/urls.py
from django.conf.urls import url,  include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('common.urls', namespace='common')),
    url(r'^customer/', include('batta_customers.urls', namespace='customer')),
    url(r'^stock/', include('batta_stock.urls', namespace='stock')),
    url(r'^sales/', include('batta_sales.urls', namespace='sales')),
    url(r'^expense/', include('batta_expense.urls', namespace='expense')),
    url(r'^staff/', include('batta_staff.urls', namespace='staff')),
    url(r'^koyla/', include('batta_koylas.urls', namespace='koyla')),
    url(r'^other/expense/', include('other_expense.urls', namespace='other_expense')),
    url(r'^account/', include('batta_account.urls', namespace='account')),

]

templates/base.html
<!DOCTYPE html>
{% load static %}
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">

    <title>Developed By | 03331340752</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <!--external css-->
    <link href="{% static 'font-awesome/css/font-awesome.css' %}" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/zabuto_calendar.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'js/gritter/css/jquery.gritter.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'lineicons/style.css' %}">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/style-responsive.css' %}" rel="stylesheet">

    <script src="{% static 'js/chart-master/Chart.js' %}"></script>
</head>

<body>

<section id="container" >
    <!-- **********************************************************************************************************************************************************
    TOP BAR CONTENT & NOTIFICATIONS
    *********************************************************************************************************************************************************** -->
    <!--header start-->
    <header class="header black-bg">
        <div class="sidebar-toggle-box">
            <div class="fa fa-bars tooltips" data-placement="right" data-original-title="Toggle Navigation"></div>
        </div>
        <!--logo start-->
        <a href="{% url 'common:index' %}" class="logo"><b>Nawab Bricks & Manufacturs</b></a>
        <!--logo end-->
        <div class="top-menu">
            <ul class="nav pull-right top-menu">
                <li><a class="logout" href="{% url 'common:logout' %}">Logout</a></li>
            </ul>
        </div>
    </header>
    <!--header end-->

    <!-- **********************************************************************************************************************************************************
    MAIN SIDEBAR MENU
    *********************************************************************************************************************************************************** -->
    <!--sidebar start-->
    <aside>
        <div id="sidebar"  class="nav-collapse ">
            <!-- sidebar menu start-->
            <ul class="sidebar-menu" id="nav-accordion">

                {#<p class="centered"></p><a href="{% url 'common:index' %}"></a><img src="{% static 'img/logo.jpg' %}" class="img-circle" width="60">#}
                <h5 class="centered">N-B-M</h5>

                <li class="mt">
                    <a class="{% block menu_dashboard %}{% endblock %}" href="{% url 'common:index' %}">
                        <i class="fa fa-dashboard"></i>
                        <span>Dashboard</span>
                    </a>
                </li>

                <li class="sub-menu">
                    <a class="{% block menu_staff %}{% endblock %}" href="javascript:;" >
                        <i class="fa fa-eye-slash"></i>
                        <span>Staffs</span>
                    </a>
                    <ul class="sub">
                        <li class="{% block sub_menu_new_staff %}{% endblock %}"><a  href="#addstaff{% url 'staff:create' %}" data-toggle="modal" data-target="#addstaff">New Staff</a></li>
                        <li class="{% block sub_menu_all_staff %}{% endblock %}"><a  href="{% url 'staff:list' %}">All Staffs</a></li>
                        <li class="{% block menu_staff_jamah_reports %}{% endblock %}"><a href="{% url 'common:staff_jamah_reports' %}">Staffs Reports</a></li>
                    </ul>
                </li>

                <li class="sub-menu">
                    <a class="{% block menu_customers %}{% endblock %}" href="javascript:;" >
                        <i class="fa fa-desktop"></i>
                        <span>Customers</span>
                    </a>
                    <ul class="sub">
                        <li class="{% block sub_menu_new_customer %}{% endblock %}"><a href="#addcustomer{% url 'customer:add' %}" data-toggle="modal" data-target="#addcustomer">New Customer</a></li>
                        <li class="{% block sub_menu_all_customer %}{% endblock %}"><a href="{% url 'customer:list' %}">All Customers</a></li>
                        <li class="{% block menu_khatta_reports %}{% endblock %}"><a href="{% url 'common:khatta_reports' %}">Customers Khatta Reports</a></li>
                    </ul>
                </li>
                <li class="sub-menu">
                    <a href="javascript:;" class="{% block menu_sales %}{% endblock %}">
                        <i class="fa fa-exchange"></i>
                        <span>Sales</span>
                    </a>
                    <ul class="sub">
                        <li class="{% block sub_menu_create_invoice %}{% endblock %}"><a  href="{% url 'sales:create_invoice' %}">Create Invoice</a></li>
                        <li class="{% block sub_menu_invoices %}{% endblock %}"><a  href="{% url 'sales:invoices' %}">Invoices</a></li>
                    </ul>
                </li>
                <li class="sub-menu">
                    <a href="javascript:;" class="{% block menu_stocks %}{% endblock %}" >
                        <i class="fa fa-cogs"></i>
                        <span>Stocks</span>
                    </a>
                    <ul class="sub">
                        <li class="{% block sub_menu_item_add %}{% endblock %}"><a  href="{% url 'stock:item_add' %}">New Item</a></li>
                        <li class="{% block sub_menu_item_list %}{% endblock %}"><a  href="{% url 'stock:item_list' %}">Items</a></li>
                        <li class="{% block sub_menu_stock_reports %}{% endblock %}"><a  href="{% url 'stock:stock_reports' %}">Reports</a></li>
                    </ul>
                </li>

                <li class="sub-menu">
                    <a class="{% block menu_koylas %}{% endblock %}" href="javascript:;" >
                        <i class="fa fa-dribbble"></i>
                        <span>Koyla</span>
                    </a>
                    <ul class="sub">
                        <li class="{% block sub_menu_new_koyla %}{% endblock %}"><a  href="#addkoyla{% url 'koyla:add' %}" data-toggle="modal" data-target="#addkoyla">Add Koyla Name</a></li>
                        <li class="{% block sub_menu_all_koyla %}{% endblock %}"><a  href="{% url 'koyla:list' %}">Koyla List</a></li>
                    </ul>
                </li>


                <li class="sub-menu">
                    <a class="{% block menu_other_expenses %}{% endblock %}" href="javascript:;" >
                        <i class="fa fa-dribbble"></i>
                        <span>Other Expenses</span>
                    </a>
                    <ul class="sub">
                        <li class="{% block sub_menu_add %}{% endblock %}"><a  href="{% url 'other_expense:add' %}">Add Expense Name</a></li>
                        <li class="{% block sub_menu_all_expenses %}{% endblock %}"><a  href="{% url 'other_expense:list' %}">Other Expenses List</a></li>
                    </ul>
                </li>

                <li class="sub-menu">
                    <a class="{% block menu_account %}{% endblock %}" href="javascript:;" >
                        <i class="fa fa-dribbble"></i>
                        <span>Income Accounts</span>
                    </a>
                    <ul class="sub">
                        <li class="{% block sub_menu_add_account %}{% endblock %}"><a  href="{% url 'account:add' %}">Add Name</a></li>
                        <li class="{% block sub_menu_all_account %}{% endblock %}"><a  href="{% url 'account:list' %}">Lists</a></li>
                    </ul>
                </li>

                <li class="sub-menu">
                    <a href="javascript:;" class="{% block menu_income %}{% endblock %}">
                        <i class="fa fa-inbox"></i>
                        <span>Season Income</span>
                    </a>
                    <ul class="sub">
                        <li class="{% block sub_menu_create_income %}{% endblock %}"><a  href="{% url 'expense:create_income' %}">Create Income</a></li>
                        <li class="{% block sub_menu_income_list %}{% endblock %}"><a  href="{% url 'expense:income_list' %}">Income List</a></li>
                        <li class="{% block sub_menu_stock_list %}{% endblock %}"><a  href="{% url 'expense:stock_list' %}">Stock List</a></li>
                    </ul>
                </li>
                <li class="sub-menu">
                    <a href="javascript:;" class="{% block menu_expense %}{% endblock %}">
                        <i class="fa fa-book"></i>
                        <span>Season Expense</span>
                    </a>
                    <ul class="sub">
                        <li class="{% block sub_menu_create_expense %}{% endblock %}"><a  href="{% url 'expense:create_expense' %}">Create Expense</a></li>
                        <li class="{% block sub_menu_expense_details %}{% endblock %}"><a  href="{% url 'expense:expense_list' %}">Expense List</a></li>
                    </ul>
                </li>
                <li class="sub-menu">
                    <a href="javascript:;" class="{% block menu_report %}{% endblock %}">
                        <i class="fa li_world"></i>
                        <span>All Reports</span>
                    </a>
                    <ul class="sub">
                        <li class="{% block menu_reports %}{% endblock %}"><a href="{% url 'common:reports' %}">Season Reports</a></li>
                        <li class="{% block menu_expense_reports %}{% endblock %}"><a href="{% url 'common:expense_reports' %}">Expense Reports</a></li>
                        <li class="{% block menu_quality_reports %}{% endblock %}"><a href="{% url 'common:quality_reports' %}">Daily Income Reports</a></li>
                    </ul>
                </li>
                <li>
            </ul>
            <!-- sidebar menu end-->
        </div>
    </aside>
    <!--sidebar end-->

    <!-- **********************************************************************************************************************************************************
    MAIN CONTENT
    *********************************************************************************************************************************************************** -->
    <!--main content start-->
    <section id="main-content">
        <section class="wrapper">

            {% block content %}
            {% endblock %}

        </section>
    </section>
</section>

{% block scripts %}
    <!-- js placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/jquery-1.8.3.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script class="include" type="text/javascript" src="{% static 'js/jquery.dcjqaccordion.2.7.js' %}"></script>
    <script src="{% static 'js/jquery.scrollTo.min.js' %}"></script>
    <script src="{% static 'js/jquery.nicescroll.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery.sparkline.js' %}"></script>


    <!--common script for all pages-->
    <script src="{% static 'js/common-scripts.js' %}"></script>

    <script type="text/javascript" src="{% static 'js/gritter/js/jquery.gritter.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/gritter-conf.js' %}"></script>

    <!--script for this page-->
    <script src="{% static 'js/sparkline-chart.js' %}"></script>
    <script src="{% static 'js/zabuto_calendar.js' %}"></script>
    <script type="application/javascript">
        $(document).ready(function () {
            $("#date-popover").popover({html: true, trigger: "manual"});
            $("#date-popover").hide();
            $("#date-popover").click(function (e) {
                $(this).hide();
            });

            $("#my-calendar").zabuto_calendar({
                action: function () {
                    return myDateFunction(this.id, false);
                },
                action_nav: function () {
                    return myNavFunction(this.id);
                },
                ajax: {
                    url: "show_data.php?action=1",
                    modal: true
                },
                legend: [
                    {type: "text", label: "Special event", badge: "00"},
                    {type: "block", label: "Regular event", }
                ]
            });
        });


        function myNavFunction(id) {
            $("#date-popover").hide();
            var nav = $("#" + id).data("navigation");
            var to = $("#" + id).data("to");
            console.log('nav ' + nav + ' to: ' + to.month + '/' + to.year);
        }
    </script>
{% endblock %}

</body>
</html>

templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <title>Developed | khalid 03331340752</title>
    <link rel="shortcut icon" type="image/png" href="#">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <!--external css-->
    <link href="{% static 'font-awesome/css/font-awesome.css' %}" rel="stylesheet" />

    <!-- Custom styles for this template -->
    <link href="{% static 'css/login.css' %}" rel="stylesheet">
    <link href="{% static 'css/login-responsive.css' %}" rel="stylesheet">
    <style>
        .errorlist{
            display: inline-block;
            color: red;
            font-size: smaller;
            float: right;
        }
        .error-alert{
            text-align: center;
            padding-bottom: 10px;
            font-size: xx-large;
            color: red;
        }
    </style>
</head>

<body>
<div id="login-page">
    <div class="container">
        <form class="form-login" method="post" action="{% url 'common:login' %}">
            <h2 class="form-login-heading">sign in now</h2>
            <div class="login-wrap">
                {% if form.errors or form.non_field_errors %}
                    <div class="error-alert">
                        <i class="fa fa-warning pull-center"></i>
                    </div>
                {% endif %}
                {% csrf_token %}
                {% if form.non_field_errors %}
                    <div>
                        {{ form.non_field_errors }}
                    </div>
                {% endif %}
                <input type="text" class="form-control" placeholder="Username" name="username" autofocus>
                {% if form.errors %}
                    {{ form.errors.username }}
                {% endif %}
                <br>
                <input type="password" class="form-control" name="password" placeholder="Password">
                {% if form.errors %}
                    {{ form.errors.password  }}
                {% endif %}
                    <br>
                <button class="btn btn-primary btn-block" type="submit"><i class="fa fa-lock"></i> SIGN IN</button>
            </div>
        </form>
    </div>
</div>

<script src="{% static 'js/jquery.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>

templates/weekly_reports.html
{% extends 'base.html' %}
{% block menu_weekly_reports %}active{% endblock %}

{% block content %}
    {% load template_tags %}
    <style>
        table {
            table-layout:fixed;
        }
        table td {
            width: 30px;
            overflow: hidden;
            text-overflow: ellipsis;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <br>
                <div class="row remove-print-display">
                    <div class="col-lg-2 col-lg-offset-2">
{#                        <label><strong>Start Date:</strong></label>#}
                        <input type="date" class="form-control start_date" id="start_date" value="{{ start_date }}">
                    </div>
                    <div class="col-lg-2">
{#                        <label><strong>End Date:</strong></label>#}
                        <input type="date" class="form-control end_date" id="end_date" value="{{ end_date }}">
                    </div>
                    <div class="col-lg-2">
                        <select class="form-control" id="season_filter">
                            <option>All Seasons</option>
                            {% for season in seasons %}
                                <option>{{ season.season_year }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="col-lg-2">
                        <button class="btn btn-primary filter-btn">Filter</button>&nbsp;&nbsp;&nbsp;
                        <button type="button" class="btn btn-primary print-invoice-btn" onclick="PrintInvoice('print-invoices')">Print</button>
                    </div>
                </div><br/>
                {% if season_kw %}
                <div class=" col-lg-8 col-lg-offset-2 content-panel table-responsive print-invoices" id="print-invoices">
                    <u><h2 class="text-center"><a href="#">Weekly Expense ({{ season_kw }})</a></h2></u>
                    <div class="">
                        <h4 style="left: 5px"><span style="color: black; font-weight: bold">Sales</span></h4>
                        <table class="table table-striped table-advance table-hover table-bordered incoices-table">
                            <thead style="background-color: teal;">
                            <tr style="color: white">
                                <th>Item/Qualities</th>
                                <th>Bricks</th>
                                <th>Income Amount</th>
                            </tr>
                            </thead>
                            <tbody class="invoices-table-body">
                                {% for stock in stocks %}
                                    {% stock_purchased_amount stock=stock season=season_kw as purchased_stock_amount %}
                                    {% purchased_stock stock=stock season=season_kw as purchased_stock %}
                                    <tr style="color: black; font-weight: bold">
                                        <td>{{ stock.item_name|title }} ({{ stock.bhatta.code }})</td>
                                        <td>{{ purchased_stock|floatformat:'-2' }}</td>
                                        <td>{{ purchased_stock_amount|floatformat:'-2' }}</td>
                                    </tr>
                                {% endfor %}
                                <tr>
                                    <td></td>
                                    <td><strong style="color:red">Total</strong></td>
                                    <td><strong style="color:red">{{ total_income_amount|floatformat:'-2' }}</strong></td>
                                </tr>
                            </tbody>
                        </table>
                        <h4 style="left: 5px"><span style="color: black; font-weight: bold">Result</span></h4>
                        <table class="table table-striped table-advance table-hover table-bordered incoices-table">
                            <tbody>
                                <tr style="color: black; font-weight: bold">
                                    <td><strong>Total Income</strong></td>
                                    <td><strong>{{ total_income_amount|floatformat:'-2' }}</strong></td>
                                </tr>
                                <tr style="color: black; font-weight: bold">
                                    <td><strong>Total Expense</strong></td>
                                    <td><strong>{{ total_expense_amount|floatformat:'-2' }}</strong></td>
                                </tr>
                                <tr style="color: black; font-weight: bold">
                                    <td><strong style="color: red;">Profit</strong></td>
                                    <td><strong style="color: red;">{{ total_profit|floatformat:'-2' }}</strong></td>
                                </tr>
                                <tr style="color: black; font-weight: bold">
                                    <td><strong>Haji Expense</strong></td>
                                    <td><strong>{{ staff_expense|floatformat:'-2' }}</strong></td>
                                </tr>
                                <tr>
                                    <td><strong style="color: red;">Total</strong></td>
                                    <td><strong style="color: red;">{{ profit|floatformat:'-2' }}</strong></td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
    {{ block.super }}
    <script>
        $(document).ready(function(){

            $('.filter-btn').on('click', function(){
                var reports_url = '{% url "common:weekly_reports" %}';
                var start_date = $('.start_date').val();
                var end_date = $('.end_date').val();
                window.location.href = reports_url + '?season=' + $('#season_filter').val() + '&start_date=' + start_date + '&end_date=' + end_date;
            });

            $('#season_filter option:contains("{{ season_kw }}")').prop('selected',true);
        });
        function PrintInvoice(divName){
             var printContents = document.getElementById(divName).innerHTML;
             var originalContents = document.body.innerHTML;
             document.body.innerHTML = printContents;
             $('table').removeClass('table-bordered');
             $('tr').css('border', '1px solid');
             $('td').css('border', '1px solid');
             $('th').css('border', '1px solid');

             $('.remove-print-display').hide();
             $('.print-show-options').show();
             window.print();
             document.body.innerHTML = originalContents;
             $('.remove-print-display').show();
             $('.print-show-options').hide();
        }
    </script>
{% endblock %}