batta_expense/urls.py
from django.conf.urls import url

from .views import (
    AddCoalExpenseFormView, CoalExpenseListView, CoalExpenseUpdateView,
    CoalExpenseDeleteView, SeasonalExpenditureFormView,
    SeasonalExpenditureListView, SeasonalExpenditureUpdateView,
    SeasonalExpenditureDeleteView, SeasonalIncomeFormView,
    SeasonalIncomeDeleteView, SeasonalIncomeListView,
    ExpenditureAmountListView, ExpenditureAmountFormView,
    ExpenditureAmountUpdateView, SeasonalStockListView, SeasonalStockDeleteView,
    SeasonalStockFormView, KoylaAmountListView, AddKoylaAmountFormView
)


urlpatterns = [
    url(
        r'^coal/create/$', AddCoalExpenseFormView.as_view(),
        name='coal_create'
    ),
    url(
        r'^coal/list/$', CoalExpenseListView.as_view(),
        name='coal_list'
    ),
    url(
        r'^create/amount$', AddKoylaAmountFormView.as_view(),
        name='create_stock'
    ),
    url(
        r'^koyla/amount/$', KoylaAmountListView.as_view(),
        name='koyla_amount'
    ),
    url(
        r'^coal/(?P<pk>\d+)/update/$',
        CoalExpenseUpdateView.as_view(),
        name='coal_update'
    ),
    url(
        r'^coal/(?P<pk>\d+)/delete/$',
        CoalExpenseDeleteView.as_view(),
        name='coal_delete'
    ),
    url(
        r'^coal/list/(?P<season>[a-zA-Z0-9_-]+)/$',
        CoalExpenseListView.as_view(), name='coal_expense_filter'
    ),
    url(
        r'^create/$', SeasonalExpenditureFormView.as_view(),
        name='create_expense'
    ),
    url(
        r'^list/$', SeasonalExpenditureListView.as_view(),
        name='expense_list'
    ),
    url(
        r'^(?P<pk>\d+)/update/$',
        SeasonalExpenditureUpdateView.as_view(),
        name='update_expense'
    ),
    url(
        r'^(?P<pk>\d+)/delete/$',
        SeasonalExpenditureDeleteView.as_view(),
        name='delete_expense'
    ),
    url(
        r'^list/(?P<season>[a-zA-Z0-9_-]+)/$',
        SeasonalExpenditureListView.as_view(), name='expense_filter'
    ),
    url(
        r'^income/create/$', SeasonalIncomeFormView.as_view(),
        name='create_income'
    ),
    url(
        r'^income/list/$', SeasonalIncomeListView.as_view(),
        name='income_list'
    ),
    url(
        r'^income/(?P<pk>\d+)/delete/$',
        SeasonalIncomeDeleteView.as_view(),
        name='delete_income'
    ),
    url(
        r'^income/list/(?P<season>[a-zA-Z0-9_-]+)/$',
        SeasonalIncomeListView.as_view(), name='income_filter'
    ),
    url(
        r'^(?P<pk>\d+)/amount/details/$',
        ExpenditureAmountListView.as_view(),
        name='expense_amount_details'
    ),
    url(
        r'^(?P<pk>\d+)/amount/details/'
        r'start/(?P<start>.+)/end/(?P<end>.+)/$',
        ExpenditureAmountListView.as_view(),
        name='expense_amount_details_filter'
    ),
    url(
        r'^(?P<pk>\d+)/amount/add/$',
        ExpenditureAmountFormView.as_view(),
        name='expense_amount_add'
    ),
    url(
        r'^(?P<pk>\d+)/amount/update/$',
        ExpenditureAmountUpdateView.as_view(),
        name='expense_amount_update'
    ),
    url(
        r'^stock/create/$', SeasonalStockFormView.as_view(),
        name='create_stock'
    ),
    url(
        r'^stock/list/$', SeasonalStockListView.as_view(),
        name='stock_list'
    ),
    url(
        r'^stock/(?P<pk>\d+)/delete/$',
        SeasonalStockDeleteView.as_view(),
        name='delete_stock'
    ),
    url(
        r'^stock/list/(?P<season>[a-zA-Z0-9_-]+)/$',
        SeasonalStockListView.as_view(), name='income_filter'
    ),
]

common/urls.py
from django.conf.urls import url
from django.contrib import admin

from common.views import IndexView, LoginView, LogoutView, ReportsView, StaffJamahReportsView, QualityReportsView, TotalExpenseReportsView, KhattaReportsView

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(
        r'^index/(?P<season>[a-zA-Z0-9_-]+)/$',
        IndexView.as_view(), name='index_filter'
    ),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^reports/$', ReportsView.as_view(), name='reports'),
    url(r'^expense/reports/$', TotalExpenseReportsView.as_view(), name='expense_reports'),
    url(
        r'^reports/(?P<season>[a-zA-Z0-9_-]+)/$',
        ReportsView.as_view(), name='reports_filter'
    ),
    url(
        r'^khatta/reports/$', KhattaReportsView.as_view(), name='khatta_reports'
    ),
    url(
        r'^expense/reports/(?P<season>[a-zA-Z0-9_-]+)/$',
        TotalExpenseReportsView.as_view(), name='expense/reports/_filter'
    ),
    url(
        r'^quality/reports/$', QualityReportsView.as_view(),
        name='quality_reports'
    ),
    url(
        r'^staff/jamah/reports/$', StaffJamahReportsView.as_view(),
        name='staff_jamah_reports'
    ),
]

nawab_bricks_management/urls.py
from django.conf.urls import url,  include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('common.urls', namespace='common')),
    url(r'^customer/', include('batta_customers.urls', namespace='customer')),
    url(r'^stock/', include('batta_stock.urls', namespace='stock')),
    url(r'^sales/', include('batta_sales.urls', namespace='sales')),
    url(r'^expense/', include('batta_expense.urls', namespace='expense')),
    url(r'^staff/', include('batta_staff.urls', namespace='staff')),
    url(r'^koyla/', include('batta_koylas.urls', namespace='koyla')),
    url(r'^other/expense/', include('other_expense.urls', namespace='other_expense')),
    url(r'^account/', include('batta_account.urls', namespace='account')),

]

templates/seasonal_reports/add_income.html
{% extends 'base.html' %}
{% block menu_income %}active{% endblock %}
{% block sub_menu_create_income %}active{% endblock %}

{% block content %}
    <div class="col-md-6">
        <br>
        <a href="{% url 'expense:income_list' %}"><button type="button" class="btn btn-primary" style="float: left">Incomes</button></a>
        <br><br><br>
        <div class="content-panel">
            <h3 class="text-center">New Estimated Income</h3>
            <div class="panel-body">
                <form class="form-horizontal add-customer-form" action="{% url 'expense:create_income' %}" method="post" >
                    <div class="form-group">
                        <div class="col-sm-12">
                            {% csrf_token %}
                            <label><strong>Availability Type</strong></label>
                            <select class="form-control availability_type" name="availability_type">
                                <option value="Inside">Inside</option>
                                <option value="Outside">Outside</option>
                            </select>
                            <br>
                            <label><strong>Bhatta</strong></label>
                            <input type="text" class="form-control bhatta_name" name="bhatta_name" autocomplete="off" placeholder="Select Bhatta" list="bhatta_list">
                            <datalist id="bhatta_list">
                                {% for bhatta in bhattas %}
                                    <option value="{{ bhatta.name }}">{{ bhatta.code }}</option>
                                {% endfor %}
                            </datalist>
                            <br>
                            <label><strong>Season</strong></label>
                            <input type="text" class="form-control season_name" name="season_name" autocomplete="off" placeholder="Season" list="season-list">
                            <datalist id="season-list">
                                {% for season in seasons %}
                                    <option value="{{ season.season_year }}"></option>
                                {% endfor %}
                            </datalist>
                            <br>
                            <label><strong>Stock Item</strong></label>
                            <input type="text" class="form-control stock_name" name="stock_name" autocomplete="off" placeholder="Select Item" list="stock-list">
                            <datalist id="stock-list">
                                {% for stock in stocks %}
                                    <option value="{{ stock }}"></option>
                                {% endfor %}
                            </datalist>
                            <br>
                            <label><strong>Available Stock Quantity</strong></label>
                            <input type="text" class="form-control stock_quantity" name="stock_quantity" value="0"><br>
                            <label><strong>Estimate Price</strong></label>
                            <input type="text" class="form-control estimate_price" name="estimate_price" value="0"><br>
                            <label><strong>Total Amount</strong></label>
                            <input type="text" class="form-control total_amount" name="total_amount" value="0" readonly><br>
                            <button type="submit" class="btn btn-primary product-sub-btn" style="float: right">Save Income</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script>
        $(function(){
            $('.stock_name').on('change', function () {
                if ($('.availability_type').val() == 'Outside') {
                    $.post('/stock/item/available/api/',
                        {'bhatta_name': $('.bhatta_name').val(), 'item_name': $('.stock_name').val(), 'season': $('.season_name').val()},
                        function (result, status) {
                            $('.stock_quantity').val(result.available_items);
                            $('.total_amount').val(parseFloat($('.stock_quantity').val()) * parseFloat($('.estimate_price').val()));
                        });
                }
            });

            $('.estimate_price').on('change', function () {
                $('.total_amount').val(parseFloat($(this).val()) * parseFloat($('.stock_quantity').val()));
                if ($('.total_amount').val() ==  0 ) {
                    $('.total_amount').val('');
                }
            });
            $('.stock_quantity').on('change', function () {
                $('.total_amount').val(parseFloat($(this).val()) * parseFloat($('.estimate_price').val()));
                if ($('.total_amount').val() ==  0 ) {
                    $('.total_amount').val('');
                }
            });


        });
    </script>
{% endblock %}

templates/seasonal_reports/expenditure_list.html
{% extends 'base.html' %}

{% block menu_expense %}active{% endblock %}
{% block sub_menu_expense_details %}active{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-10">
                <br>
                <a href="{% url 'expense:create_expense' %}"><button type="button" class="btn btn-primary">Create Expense</button></a>
                <br><br>
                <div class="content-panel table-responsive">
                    <h2 class="text-center"><span style="color: teal; font-weight: bold">Expenditures</span></a></h2>
                    <br>
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="input-group custom-search-form col-md-12" style="left: 5px">
                                <input type="text" class="form-control search-invoice" placeholder="Search...">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                        </div>
                        <div class="col-lg-2">
                            <select class="form-control" id="season_filter">
                                <option>All Seasons</option>
                                {% for season in seasons %}
                                    <option>{{ season.season_year }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    {#<div style="float: right; padding: 12px;">#}
                        {#<strong><a href="#">Grand Total:</a></strong> <span style="color: red">{{ total_amount|floatformat:'-2' }}</span>&nbsp;&nbsp;&nbsp;#}
                    {#</div>#}
                    <hr>
                    <table class="table table-striped table-advance table-hover table-bordered incoices-table">
                        <thead style="background-color: teal;">
                        <tr style="color: white">
                            <th class="text-center"> S/No</th>
                            <th class="text-center"> Expense Name</th>
                            <th class="text-center"> Season</th>
                            <th class="text-center"> Actions</th>
                        </tr>
                        </thead>
                        <tbody class="invoices-table-body">
                        {% if not object_list %}
                            <tr><td colspan="11" class="text-center">Record Not Found</td></tr>
                        {% endif %}
                        {% for expense in object_list %}
                            <tr style="color: black; font-weight: bold">
                                <td class="text-center">{{ forloop.counter }}</td>
                                <td class="text-center">{{ expense.expense_name|title }}</td>
                                <td class="text-center">{{ expense.season.season_year }}</td>
                                <td class="text-center">
                                    <a href="{% url 'expense:delete_expense' pk=expense.id %}" onclick="return confirm('&#9940 Are you sure you want to delete this item &#9940;')"><button class="btn btn-danger btn-xs">Delete</button></a>
                                    <a href="{% url 'expense:update_expense' pk=expense.id %}"><button class="btn btn-primary btn-xs">Update</button></a>
                                    <a href="{% url 'expense:expense_amount_details' pk=expense.id %}"><button class="btn btn-success btn-xs">View Details</button></a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

{% endblock %}
{% block scripts %}
    {{ block.super }}
    <script>
        $(document).ready(function(){
            $(".search-invoice").on("keyup", function() {
                var value = $(this).val().toLowerCase();
                $(".invoices-table-body tr").filter(function() {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });

            var expense_url = '{% url "expense:expense_list" %}';
            $('#season_filter').on('change', function () {
                if ($(this).val() == 'All Seasons') {
                    window.location.href = expense_url
                } else {
                    window.location.href = expense_url + $(this).val() + '/';
                }
            });
            $('#season_filter option:contains("{{ season_kw }}")').prop('selected',true);

        });
    </script>
{% endblock %}

templates/seasonal_reports/expense_amount_list.html
{% extends 'base.html' %}
{% block menu_expense %}active{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-11">
                <br>
                <a href="{% url 'expense:expense_amount_add' pk=expense.id %}"><button type="button" class="btn btn-primary">New Expense</button></a>
                <button type="button" class="btn btn-primary print-invoice-btn" onclick="PrintInvoice('print-invoices')">Print Invoice</button>
                <br><br>
                <div class=" content-panel table-responsive print-invoices" id="print-invoices">
                    <h2 class="text-center"><a href="#">{{ expense.expense_name|title }} | {{ expense.season.season_year }}</a></h2>
                        <div class="col-lg-12">
                            <div class="col-lg-4 remove-print-display">
                                <label><strong><span style="color: black">Start Date:</span></strong></label>
                                <input type="date" class="form-control start_date" id="start_date" value="{{ start_date }}">
                            </div>
                            <div class="col-lg-4 remove-print-display">
                                <label><strong><span style="color: black">End Date:</span></strong></label>
                                <input type="date" class="form-control end_date" id="end_date" value="{{ end_date }}">
                            </div>
                            <div class="col-lg-4 remove-print-display">
                                <label><strong>&nbsp;</strong></label><br>
                                <button class="btn btn-primary filter-btn">Filter</button>
                            </div>
                        </div>
                        <br><br><br><br>
                    <div style="float: right; padding: 12px;">
                         <strong><span style="color: #428bca !important; font-size: 16px">Total Amount:</span></strong><span style="color: red !important; font-size: 14px"> {{total_amount|floatformat:'-2' }}</span>&nbsp;&nbsp;&nbsp;
                      </div>
                    <hr>
                    <table class="table table-striped table-advance table-hover table-bordered incoices-table">
                        <thead style="background-color: teal !important;">
                        <tr style="color: white">
                            <th class="text-center">Date</th>
                            <th class="text-center">Amount</th>
                            <th class="text-center">Details</th>
                            <th class="remove-print-display text-center">Actions</th>
                        </tr>
                        </thead>
                        <tbody class="invoices-table-body">
                        {% if not expense_amount_list %}
                            <tr><td colspan="11" class="text-center">Record Not Found</td></tr>
                        {% endif %}
                        {% for expense in expense_amount_list %}
                            <tr style="color: black; font-weight: bold">
                                <td class="text-center">{{ expense.added_date }}</td>
                                <td class="text-center">{{ expense.amount|floatformat:'-3' }}</td>
                                <td class="text-center">{{ expense.details }}</td>
                                <td class="remove-print-display text-center">
                                    <a href="{% url 'expense:expense_amount_update' pk=expense.id %}"><button class="btn btn-primary btn-xs">Update</button></a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block scripts %}
{{ block.super }}
    <script>
        $(function () {
            $('.filter-btn').on('click', function () {
                var error = false;
                if ($('.start_date').val() == '') {
                    $('.start_date').css('border', '1px solid red');
                    error = true;
                }


                if($('.end_date').val() == '') {
                    $('.end_date').css('border', '1px solid red');
                    error = true;
                }

                if(error == true) {
                    return;
                }

                var start_date = $('.start_date').val();
                var end_date = $('.end_date').val();

                var expense_url = '{% url "expense:expense_amount_details" pk=expense.id %}';

                window.location.href = expense_url + 'start/' + start_date + '/end/' + end_date + '/';


            });

        });
        function PrintInvoice(divName){
             var printContents = document.getElementById(divName).innerHTML;
             var originalContents = document.body.innerHTML;
             document.body.innerHTML = printContents;
             $('table').removeClass('table-bordered');
             $('tr').css('border', '1px solid');
             $('td').css('border', '1px solid');
             $('th').css('border', '1px solid');
             $('.remove-print-display').hide();
             window.print();
             $('.remove-print-display').show();
             document.body.innerHTML = originalContents;
        }
    </script>
{% endblock %}

templates/seasonal_reports/income_list.html
{% extends 'base.html' %}
{% block menu_income %}active{% endblock %}
{% block sub_menu_income_list %}active{% endblock %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-lg-10">
                <br>
                <a href="{% url 'expense:create_income' %}"><button type="button" class="btn btn-primary">Add Income</button></a>
                <br><br>
                <div class="content-panel table-responsive">
                    <h2 class="text-center">Seasonal Income</a></h2>
                    <div class="print-show-options" style="display:ruby-text-container; color: teal">
                        {% if season_kw %}
                            <h3 class="text-center">Season: {{ season_kw }}</h3>
                        {% endif %}
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="input-group custom-search-form col-md-12" style="left: 5px">
                                <input type="text" class="form-control search-invoice" placeholder="Search...">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                        </div>
                        <div class="col-lg-2">
                            <select class="form-control" id="season_filter">
                                <option>All Seasons</option>
                                {% for season in seasons %}
                                    <option>{{ season.season_year }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
{#                    <div style="float: right; padding: 12px;">#}
{#                        <strong>Total Bricks:</strong> <span style="color: red">{{ total_quantity|floatformat:'-2' }}</span>&nbsp;&nbsp;&nbsp;#}
{#                        <strong>Grand Total:</strong> <span style="color: red">{{ grand_total|floatformat:'-2' }}</span>#}
{#                    </div>#}
                    <hr>
                    <table class="table table-striped table-advance table-hover table-bordered incoices-table">
                        <thead style="background-color: teal;">
                        <tr style="color: white">
                            <th><i class=" fa fa-edit"></i> Item</th>
                            <th><i class=" fa fa-edit"></i> Availability</th>
                            <th><i class="fa fa-bullhorn"></i> Quantity</th>
                            <th><i class="fa fa-bullhorn"></i> Estimated Price</th>
                            <th><i class="fa fa-bullhorn"></i> Total Amount</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody class="invoices-table-body">
                        {% if not object_list %}
                            <tr><td colspan="11" class="text-center">Record Not Found</td></tr>
                        {% endif %}
                        {% for income in object_list %}
                            <tr style="color: black; font-weight: bold">
                                <td>{{ income.stock.item_name|title }}</td>
                                <td>{{ income.availability_type }}</td>
                                <td>{{ income.stock_quantity|floatformat:'-2' }}</td>
                                <td>{{ income.estimate_price|floatformat:'-2' }}</td>
                                <td>{{ income.total_amount|floatformat:'-2' }}</td>
                                <td>
                                    <a href="{% url 'expense:delete_income' pk=income.id %}"><button class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i></button></a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script>
        $(document).ready(function(){
            $(".search-invoice").on("keyup", function() {
                var value = $(this).val().toLowerCase();
                $(".invoices-table-body tr").filter(function() {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });

            var income_url = '{% url "expense:income_list" %}';
            $('#season_filter').on('change', function () {
                if ($(this).val() == 'All Seasons') {
                    window.location.href = income_url
                } else {
                    window.location.href = income_url + $(this).val() + '/';
                }
            });
            $('#season_filter option:contains("{{ season_kw }}")').prop('selected',true);

        });
    </script>
{% endblock %}

templates/seasonal_reports/stock_list.html
{% extends 'base.html' %}
{% block menu_income %}active{% endblock %}
{% block sub_menu_stock_list %}active{% endblock %}

{% block content %}
        <div class="row">
            <div class="col-lg-10">
                <br>
                <a href="{% url 'expense:create_stock' %}"><button type="button" class="btn btn-primary">Add Stocks</button></a>
                <br><br>
                <div class="content-panel table-responsive">
                    <h2 class="text-center"><a href="#">Seasonal Old Remaining Stock</a></h2>
                    <br>
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="input-group custom-search-form col-md-12" style="left: 5px">
                                <input type="text" class="form-control search-invoice" placeholder="Search...">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                        </div>
                        <div class="col-lg-2">
                            <select class="form-control" id="season_filter">
                                <option>All Seasons</option>
                                {% for season in seasons %}
                                    <option>{{ season.season_year }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <hr>
                    <table class="table table-striped table-advance table-hover table-bordered incoices-table">
                        <thead style="background-color: teal;">
                        <tr style="color: white">
                            <th><i class=" fa fa-bookmark"></i> Season</th>
                            <th><i class="fa fa-bullhorn"></i> Total Amount</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody class="invoices-table-body">
                        {% if not object_list %}
                            <tr><td colspan="11" class="text-center">Record Not Found</td></tr>
                        {% endif %}
                        {% for stock in object_list %}
                            <tr style="color: black; font-weight: bold">
                                <td>{{ stock.season.season_year }}</td>
                                <td>{{ stock.stock_amount|floatformat:'-2' }}</td>
                                <td>
                                    <a href="{% url 'expense:delete_stock' pk=stock.id %}"><button class="btn btn-danger btn-xs"><i class="fa fa-trash-o"></i></button></a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block scripts %}
    {{ block.super }}
    <script>
        $(document).ready(function(){
            $(".search-invoice").on("keyup", function() {
                var value = $(this).val().toLowerCase();
                $(".invoices-table-body tr").filter(function() {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });

            var income_url = '{% url "expense:stock_list" %}';
            $('#season_filter').on('change', function () {
                if ($(this).val() == 'All Seasons') {
                    window.location.href = income_url
                } else {
                    window.location.href = income_url + $(this).val() + '/';
                }
            });
            $('#season_filter option:contains("{{ season_kw }}")').prop('selected',true);

        });
    </script>
{% endblock %}

templates/seasonal_reports/update_income.html
{% extends 'base.html' %}

{% block content %}

{% endblock %}