batta_sales/urls.py
from django.conf.urls import url
from . import views
from batta_sales.views import (
    CreateInvoiceFormView, StockItemsAPIView, CreateInvoiceAPIView,
    InvoicesListView, InvoiceDetailsView
)

urlpatterns = [
    url(r'^invoices/$', InvoicesListView.as_view(), name='invoices'),
    url(
        r'^invoices/(?P<season>[a-zA-Z0-9_-]+)/$',
        InvoicesListView.as_view(), name='invoices_filter'
    ),
    url(r'^create/$', CreateInvoiceFormView.as_view(), name='create_invoice'),
    url(r'^(?P<pk>\d+)/invoice/delete/$', views.DeleteInvoices, name='invoice_delete'),
    url(
        r'stock/items/api/$', StockItemsAPIView.as_view(),
        name='stock_items_api'
    ),
    url(
        r'create/invoice/api/$', CreateInvoiceAPIView.as_view(),
        name='create_invoice_api'
    ),
    url(
        r'^invoice/(?P<pk>\d+)/details/$',
        InvoiceDetailsView.as_view(),
        name='invoice_details'
    ),
]

batta_staff/urls.py
from django.conf.urls import url

from batta_staff.views import (
    StaffListView, CreateStaffView, StaffCreditView, StaffDebitView,
    StaffUpdateView, NormalStaffDetailsView, AdvanceStaffCreditFormView,
    AdvanceStaffDetails, AdvanceStaffCreditUpdateView, NormalStaffDetailsReportsView,
    WeeklyStaffDetailsReportsView, OtherStaffCreditFormView, OtherStaffDebitView, OtherStaffDetails
)

urlpatterns = [
    url(r'^list/$', StaffListView.as_view(), name='list'),
    url(
        r'^list/(?P<season>[a-zA-Z0-9_-]+)/$',
        StaffListView.as_view(), name='list_filter'
    ),
    url(r'^create/$', CreateStaffView.as_view(), name='create'),
    url(
        r'^(?P<pk>\d+)/update/$',
        StaffUpdateView.as_view(), name='update'
     ),
    url(
        r'^(?P<pk>\d+)/credit/$',
        StaffCreditView.as_view(), name='credit'
     ),
    url(
        r'^(?P<pk>\d+)/debit/$',
        StaffDebitView.as_view(), name='debit'
    ),
    url(
        r'^(?P<pk>\d+)/details/$',
        NormalStaffDetailsView.as_view(), name='details'
    ),
    url(
        r'^(?P<pk>\d+)/details/reports/$',
        NormalStaffDetailsReportsView.as_view(), name='details_reports'
    ),
    url(
        r'^(?P<pk>\d+)/details/reports/(?P<season>[a-zA-Z0-9_-]+)/$',
        NormalStaffDetailsReportsView.as_view(), name='details_reports_fiter'
    ),
    url(
        r'^(?P<pk>\d+)/weekly/reports/$',
        WeeklyStaffDetailsReportsView.as_view(), name='weekly_reports'
    ),
    url(
        r'^(?P<pk>\d+)/weekly/reports/(?P<season>[a-zA-Z0-9_-]+)/$',
        WeeklyStaffDetailsReportsView.as_view(), name='weekly_reports_fiter'
    ),
    url(
        r'^(?P<pk>\d+)/credit/advance/$',
        AdvanceStaffCreditFormView.as_view(), name='credit_advance'
    ),
    url(
        r'^(?P<pk>\d+)/credit/update/$',
        AdvanceStaffCreditUpdateView.as_view(), name='update_advance'
    ),
    url(
        r'^(?P<pk>\d+)/details/advance/$',
        AdvanceStaffDetails.as_view(), name='details_advance'
    ),
    url(
        r'^(?P<pk>\d+)/details/advance/(?P<season>[a-zA-Z0-9_-]+)/$',
        AdvanceStaffDetails.as_view(), name='details_advance_fiter'
    ),
    url(
        r'^(?P<pk>\d+)/credit/other/$',
        OtherStaffCreditFormView.as_view(), name='credit_other'
    ),
    url(
        r'^(?P<pk>\d+)/debit/other/$',
        OtherStaffDebitView.as_view(), name='debit_other'
    ),
    url(
        r'^(?P<pk>\d+)/details/other/$',
        OtherStaffDetails.as_view(), name='details_other'
    ),
    url(
        r'^(?P<pk>\d+)/details/other/(?P<season>[a-zA-Z0-9_-]+)/$',
        OtherStaffDetails.as_view(), name='details_other_fiter'
    ),
]

common/urls.py
from django.conf.urls import url
from django.contrib import admin

from common.views import IndexView, LoginView, LogoutView, ReportsView, StaffJamahReportsView, QualityReportsView, TotalExpenseReportsView, KhattaReportsView

urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index'),
    url(
        r'^index/(?P<season>[a-zA-Z0-9_-]+)/$',
        IndexView.as_view(), name='index_filter'
    ),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^reports/$', ReportsView.as_view(), name='reports'),
    url(r'^expense/reports/$', TotalExpenseReportsView.as_view(), name='expense_reports'),
    url(
        r'^reports/(?P<season>[a-zA-Z0-9_-]+)/$',
        ReportsView.as_view(), name='reports_filter'
    ),
    url(
        r'^khatta/reports/$', KhattaReportsView.as_view(), name='khatta_reports'
    ),
    url(
        r'^expense/reports/(?P<season>[a-zA-Z0-9_-]+)/$',
        TotalExpenseReportsView.as_view(), name='expense/reports/_filter'
    ),
    url(
        r'^quality/reports/$', QualityReportsView.as_view(),
        name='quality_reports'
    ),
    url(
        r'^staff/jamah/reports/$', StaffJamahReportsView.as_view(),
        name='staff_jamah_reports'
    ),
]

nawab_bricks_management/urls.py
from django.conf.urls import url,  include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('common.urls', namespace='common')),
    url(r'^customer/', include('batta_customers.urls', namespace='customer')),
    url(r'^stock/', include('batta_stock.urls', namespace='stock')),
    url(r'^sales/', include('batta_sales.urls', namespace='sales')),
    url(r'^expense/', include('batta_expense.urls', namespace='expense')),
    url(r'^staff/', include('batta_staff.urls', namespace='staff')),
    url(r'^koyla/', include('batta_koylas.urls', namespace='koyla')),
    url(r'^other/expense/', include('other_expense.urls', namespace='other_expense')),
    url(r'^account/', include('batta_account.urls', namespace='account')),

]

other_expense/urls.py
from django.conf.urls import url
from . import views
from other_expense.views import (
    OtherExpenses, AddOtherExpenseFormView, OtherExpenseUpdateView, OtherExpenseDeleteView,
    DebitDieselLedgerView, CreditDieselLedgerView, DieselDetailsView, DieselUpdateView, DieselInvoicesView,
    DebitMittiLedgerView, CreditMittiLedgerView, MittiDetailsView, MittiUpdateView, MittiInvoicesView
)

urlpatterns = [
    url(r'^add/$', AddOtherExpenseFormView.as_view(), name='add'),
    url(r'^$', OtherExpenses.as_view(), name='list'),
    url(r'^(?P<pk>\d+)/update/$', OtherExpenseUpdateView.as_view(), name='update'),
    url(r'^(?P<pk>\d+)/delete/$', OtherExpenseDeleteView.as_view(), name='delete'),

    url(r'^(?P<pk>\d+)/debit/$', DebitDieselLedgerView.as_view(), name='debit'),
    url(r'^(?P<pk>\d+)/credit/$', CreditDieselLedgerView.as_view(), name='credit'),
    url(r'^(?P<pk>\d+)/diesel/details/$', DieselDetailsView.as_view(), name='diesel_details'),
    url(r'^(?P<pk>\d+)/diesel/update/$', DieselUpdateView.as_view(), name='diesel_update'),
    url(r'^(?P<pk>\d+)/diesel/delete/$', views.DeleteDieselLedger, name='diesel_delete'),
    url(
        r'^(?P<other_expense_id>\d+)/invoices/$',
        DieselInvoicesView.as_view(),
        name='invoices'
    ),
    url(
        r'^(?P<other_expense_id>\d+)/invoices/'
        r'start/(?P<start>.+)/end/(?P<end>.+)/$',
        DieselInvoicesView.as_view(),
        name='invoices_filter'
    ),

    url(r'^(?P<pk>\d+)/mitti/credit/$', CreditMittiLedgerView.as_view(), name='mitti_credit'),
    url(r'^(?P<pk>\d+)/mitti/debit/$', DebitMittiLedgerView.as_view(), name='mitti_debit'),
    url(r'^(?P<pk>\d+)/mitti/details/$', MittiDetailsView.as_view(), name='mitti_details'),
    url(r'^(?P<pk>\d+)/mitti/update/$', MittiUpdateView.as_view(), name='mitti_update'),
    url(r'^(?P<pk>\d+)/mitti/delete/$', views.DeleteMittidebit, name='mitti_delete'),
    url(
        r'^(?P<other_expense_id>\d+)/mitti/invoices/$',
        MittiInvoicesView.as_view(),
        name='mitti_invoices'
    ),
    url(
        r'^(?P<other_expense_id>\d+)/mitti/invoices/'
        r'start/(?P<start>.+)/end/(?P<end>.+)/$',
        MittiInvoicesView.as_view(),
        name='mitti_invoices_filter'
    ),

]

common/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models

from django.db.models.signals import post_save
from django.contrib.auth.models import User

from django.utils import timezone


class DatedModel(models.Model):
    class Meta:
        abstract = True

    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateTimeField(auto_now_add=True)


class UserProfile(models.Model):
    USER_TYPE_OWNER = 'owner'
    USER_TYPE_CASHIER = 'cashier'
    USER_TYPE_STOCK = 'stock'

    USER_TYPES = (
        (USER_TYPE_OWNER, 'Owner'),
        (USER_TYPE_CASHIER, 'Cashier'),
        (USER_TYPE_STOCK, 'Stock Manager'),
    )

    user = models.OneToOneField(User, related_name='user_profile')
    user_type = models.CharField(
        max_length=100, choices=USER_TYPES, default=USER_TYPE_OWNER
    )
    address = models.TextField(max_length=512, blank=True, null=True)
    phone_no = models.CharField(max_length=13, blank=True, null=True)
    mobile_no = models.CharField(max_length=13, blank=True, null=True)
    picture = models.ImageField(
        upload_to='images/profile/picture/', max_length=1024, blank=True
    )
    date_of_birth = models.DateField(blank=True, null=True)

    def __unicode__(self):
        return self.user.username


# Signal Functions
def create_profile(sender, instance, created, **kwargs):
    """
    The functions used to check if user profile is not created
    and created the user profile without saving role and hospital
    :param sender:
    :param instance:
    :param created:
    :param kwargs:
    :return:
    """
    if created and not UserProfile.objects.filter(user=instance):
        return UserProfile.objects.create(
            user=instance,
            user_type=UserProfile.USER_TYPE_OWNER
        )


# Signals
post_save.connect(create_profile, sender=User)


class Bhatta(models.Model):
    name = models.CharField(max_length=200)
    code = models.CharField(max_length=100)

    def __unicode__(self):
        return '%s (%s)' % (self.name, self.code)


class Season(models.Model):
    TYPE_ACTIVATE = 'Activate'
    TYPE_DEACTIVATE = 'Deactivate'

    ACTION = (
        (TYPE_ACTIVATE, 'Activate'),
        (TYPE_DEACTIVATE, 'Deactivate'),
    )
    date_added = models.DateField(
        default=timezone.now, blank=True, null=True)
    season_year = models.CharField(max_length=20)
    season_status = models.CharField(max_length=100, choices=ACTION, blank=True, null=True)

    def __unicode__(self):
        return self.season_year

templates/other_expenses/add.html
{% extends 'base.html' %}
{% block menu_other_expenses %}active{% endblock %}
{% block sub_menu_add %}active{% endblock %}

{% block content %}
    <div class="col-md-6">
        <br>
        <a href="{% url 'koyla:list' %}"><button type="button" class="btn btn-primary" style="float: left">Go To List</button></a>
        <br><br><br>
        <div class="content-panel">
            <h3 class="text-center">Add Expenses</h3>
            <div class="panel-body">
                <form class="form-horizontal add-customer-form" action="#" method="post" >
                    <div class="form-group">
                        <div class="col-sm-12">
                            {% csrf_token %}

                            <label class="form-control-label" name="bhatta_name">Bhatta<span style="color:red">*</span></label>
                            <select class="form-control" name="bhatta_name">
                                {% for bhatta in bhatta_list %}
                                <option value="{{ bhatta.name }}">{{ bhatta.name }}</option>
                                {% endfor %}
                            </select>
                            <br>

                            <label><strong>Expense Name</strong></label>
                            <input type="text" class="form-control name" name="name" placeholder="Expense Name"><br>

                            <label class="form-control-label" name="expense_type">Department<span style="color:red">*</span></label>
                            <select class="form-control" name="expense_type">
                                <option value="diesel">Diesel</option>
                                <option value="Mitti">Mitti</option>
                            </select>
                            <br>

                            <label><strong>Mobile No.</strong></label>
                            <input type="text" class="form-control mobile_no" name="mobile_no" placeholder="Mobile No.">
                            <br>

                            <button type="submit" class="btn btn-primary product-sub-btn" style="float: right">Save Expense</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/other_expenses/list.html
{% extends 'base.html' %}
{% block menu_other_expenses %}active{% endblock %}
{% block sub_menu_all_expenses %}active{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-10">
                <br>
                <br><br>
                <div class="content-panel table-responsive">
                    <h2 class="text-center"><span style="color: teal; font-weight: bold">Other Expenses List</span></h2>
                    <br>
                    <div class="row">
                        <div class="col-lg-6">
                            <div class="input-group custom-search-form col-md-12" style="left: 5px">
                                <input type="text" class="form-control search-invoice" placeholder="Search...">
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button">
                                        <i class="fa fa-search"></i>
                                    </button>
                                </span>
                            </div>
                        </div>
                    </div>
                    <hr>
                    <table class="table table-striped table-advance table-hover table-bordered incoices-table">
                        <thead style="background-color: teal !important;">
                        <tr style="color: white">
                            <th class="text-center"> S / No</th>
                            <th class="text-center"> Expenses Name</th>
                            <th class="text-center"> Mobile</th>
                            <th class="text-center"> Department</th>
                            <th class="text-center"> Actions</th>
                        </tr>
                        </thead>
                        <tbody class="invoices-table-body">
                        {% if not object_list %}
                            <tr><td colspan="11" class="text-center">Record Not Found</td></tr>
                        {% endif %}
                        {% for other_expense in object_list %}
                            <tr style="color: black; font-weight: bold">
                                <td class="text-center">{{ forloop.counter }}</td>
                                <td class="text-center">{{ other_expense.name|title }}</td>
                                <td class="text-center">{{ other_expense.mobile_no }}</td>
                                <td class="text-center">{{ other_expense.expense_type }}</td>
                                <td class="text-center">
                                    {#<a href="{% url 'other_expense:delete' pk=other_expense.id %}" onclick="return confirm('&#9940 Are you sure you want to delete this item &#9940;')"><button class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-trash"></span></button></a>#}
                                    {#<a href="{% url 'other_expense:update' pk=other_expense.id %}"><button class="btn btn-success btn-xs"><span class="glyphicon glyphicon-pencil"></span></button></a>#}
                                    {% if other_expense.expense_type == other_expense.EXPENSE_DIESEL %}
                                    <a href="{% url 'other_expense:diesel_details' pk=other_expense.id %}"><button class="btn btn-primary btn-xs">Add Diesel</button></a>
                                    <a href="{% url 'other_expense:invoices' other_expense_id=other_expense.id %}"><button class="btn btn-danger btn-xs">Diesel Reports</button></a>
                                    {% else %}
                                    {% if other_expense.expense_type == other_expense.EXPENSE_MITTI %}
                                    <a href="{% url 'other_expense:mitti_details' pk=other_expense.id %}"><button class="btn btn-primary btn-xs">Add Mitti</button></a>
                                    <a href="{% url 'other_expense:mitti_invoices' other_expense_id=other_expense.id %}"><button class="btn btn-danger btn-xs">Mitti Reports</button></a>
                                    {% endif %}
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                    {% if paginator.page_range|length > 1 %}
                        <div class="text-center">
                            <ul class="pagination">
                                <li><a  style="background-color: #3070A8; color: white" class="page_previous" href="{% if page_obj.has_previous %}{{ request.path }}?page={{ page_obj.previous_page_number }}{% else %}#{% endif %}" title="Previous"><<</a></li>
                                <li><a style="background-color: #3070A8; color: white" class="page_next" href="{% if page_obj.has_next %}{{ request.path }}?page={{ page_obj.next_page_number }}{% else %}#{% endif %}" title="Next">>></a></li>
                            </ul>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

{% endblock %}
{% block scripts %}
    {{ block.super }}
    <script>
        $(document).ready(function(){
            $(".search-invoice").on("keyup", function() {
                var value = $(this).val().toLowerCase();
                $(".invoices-table-body tr").filter(function() {
                    $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                });
            });

            var other_expense_url = '{% url "other_expense:list" %}';
            $('#season_filter').on('change', function () {
                if ($(this).val() == 'All Seasons') {
                    window.location.href = other_expense_url
                } else {
                    window.location.href = other_expense_url + $(this).val() + '/';
                }
            });
            $('#season_filter option:contains("{{ season_kw }}")').prop('selected',true);

        });
    </script>
{% endblock %}

templates/other_expenses/update.html
{% extends 'base.html' %}
{% block menu_other_expenses %}active{% endblock %}
{% block sub_menu_all_expenses %}active{% endblock %}

{% block content %}
    <div class="col-md-6">
        <br>
        <a href="{% url 'other_expense:list' %}"><button type="button" class="btn btn-primary" style="float: left">Expense</button></a>
        <br><br><br>
        <div class="content-panel">
            <h3 class="text-center">Update | <small>{{ object.name }}</small></h3>
            <div class="panel-body">
                <form class="form-horizontal add-customer-form" action="#" method="post" >
                    <div class="form-group">
                        <div class="col-sm-12">
                            {% csrf_token %}
                            <input type="text" class="form-control name" name="name" placeholder="Owner Name" value="{{ object.name }}"><br>
                            <input type="text" class="form-control mobile_no" name="mobile_no" placeholder="Mobile No." value="{{ object.mobile_no }}"><br>
                            <input type="text" class="form-control department" name="expense_type" placeholder="Add Department" value="{{ object.expense_type }}"><br>
                            <input type="text" class="form-control bhatta_name" name="bhatta_name" autocomplete="off" placeholder="Select Bhatta" value="{{ object.bhatta.name }}" list="bhatta_list">
                            <datalist id="bhatta_list">
                                {% for bhatta in bhatta_list %}
                                    <option value="{{ bhatta.name }}">{{ bhatta.code }}</option>
                                {% endfor %}
                            </datalist>
                            <br>
                            <button type="submit" class="btn btn-primary product-sub-btn" style="float: right">Save And Update</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock %}